/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: xingkai_42.c                                          *
* Font:        华文行楷                                              *
* Height:      42                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  42                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\CS9929SY\CS9929SY\CS9929SY\source\Document\42华文行楷.txt*
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\CS9929SY\CS9929SY\CS9929SY\source\Document\42华文行楷.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontxingkai_42;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_4EAC[132] = { /* code 4EAC */
  ________,___XXXXX,X_______,________,
  ________,____XXXX,XX______,________,
  ________,_____XXX,XXX_____,________,
  ________,____XXXX,XXX_____,________,
  ________,___XXXXX,XX______,________,
  ________,__XXXXXX,_XXXXXX_,________,
  ________,XXXXX_XX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,XXXXXXXX,XXXXXX__,________,
  __XX__XX,XXXXXX_X,XXXXX___,________,
  _XXXXXXX,XXXX__XX,XXXX____,________,
  XXXXXXXX,XX___XXX,XXX_____,________,
  XXXXXXXX,X___XXXX,XX______,________,
  _XXXXXX_,___XXXXX,XXXXX___,________,
  _XXXX___,__XXXXXX,XXXXXX__,________,
  ________,_XXXXXXX,X_XXXX__,________,
  ________,XXXXXXX_,__XXXX__,________,
  _______X,XXXXXXX_,_XXXX___,________,
  ______XX,XXXXXXXX,XXXX____,________,
  ______XX,XXXXXXXX,XXX_____,________,
  _______X,XXXXXXXX,X_______,________,
  ________,XX__XXXX,X_______,________,
  ________,______XX,X_______,________,
  ________,______XX,XXXXXXX_,________,
  ____XX__,____XXXX,X____XXX,X_______,
  ____XXX_,__XXX_XX,X____XXX,XX______,
  ____XXXX,XXX___XX,X_XXXXXX,XXX_____,
  ____XXXX,XXXX__XX,X___XXXX,XXX_____,
  ___XXXXX,XXXXXXXX,X____XXX,XX______,
  ___XXXXX,__XXXXXX,X______X,XX______,
  ____XXX_,___XXXXX,X_______,________,
  ____XXX_,_____XXX,X_______,________,
  ________,______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_4EEA[145] = { /* code 4EEA */
  _______X,X_______,________,________,________,
  ________,XX______,_____XXX,X_______,________,
  _______X,XXXX____,____XX_X,XXX_____,________,
  _______X,XXXX____,____XX_X,XXXX____,________,
  ______XX,XXXX____,___XX__X,XXXX____,________,
  ______XX,XXXX____,___XX_XX,XXXX____,________,
  _____XXX,XXX_____,XXXXX_XX,XXX_____,________,
  ____XXXX,XX______,XXXXX_XX,XXX_____,________,
  ____XXXX,XX______,XXXXXXXX,XXX_____,________,
  ___XXXXX,X_______,XXXXXXXX,XX______,________,
  __XXXXXX,________,XXXXXXXX,XX______,________,
  _XXXXXXX,________,_XXXXXXX,X_______,________,
  XXXXXXX_,XXXXXXXX,_XXXXXXX,X_______,________,
  XXXXXX_X,XXXXXXXX,XX__XXXX,X_______,________,
  XXXXXX__,____XXXX,XXXXXXXX,________,________,
  XXXXXXX_,______XX,XXXXXXXX,________,________,
  _XX__XX_,________,XXXXXXXX,________,________,
  _____XXX,X_______,_XXXXXX_,________,________,
  _____XXX,________,_XXXXXXX,________,________,
  _____XXX,________,XXXXXXXX,X_______,________,
  _____XXX,X______X,XXXXXXXX,XXX_____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  _____XXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,___XXXXX,XXX___XX,XXXXXXXX,XX______,
  ____XXXX,________,________,XXXXXXXX,XXXX____,
  ____XXXX,________,________,_XXXXXXX,XXXXX___,
  _____XXX,________,________,___XXXXX,XXXXXX__,
  _____XXX,________,________,_____XXX,XXXXX___,
  _____XX_,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_5357[140] = { /* code 5357 */
  ________,_XXX____,________,________,
  ________,XXXXXX__,________,________,
  ________,__XXXXX_,________,________,
  ________,__XXXXX_,________,________,
  ________,__XXXXX_,________,________,
  ________,__XXXXX_,________,________,
  ________,__XXXXXX,X_______,________,
  ________,__XXXXXX,XXX_____,________,
  ________,__XXXXXX,XXXX____,________,
  ________,_XXXXXXX,XX______,________,
  ______XX,XXXXXXX_,________,________,
  ___XXXXX,XXXXXX__,________,________,
  ____XXXX,XXXXXXXX,________,________,
  _____XXX,XXXXXXXX,XX______,________,
  ________,_XXXXX_X,XX______,________,
  ________,_XXXX__X,XXXXXXXX,________,
  ________,_XXXXXXX,XXXXXXXX,XX______,
  _______X,XXXXXXXX,X_____XX,XXX_____,
  ______XX,XXXXXXXX,X______X,XXXX____,
  _XXXXXXX,XXXX_XXX,_______X,XXXX____,
  XXXXXXXX,XXXX_XXX,XX_____X,XXX_____,
  XXXXXX__,XXXXXXXX,XX_____X,XXX_____,
  XXXXX___,XXXXXXXX,XX_____X,XXX_____,
  _XXX___X,XXXXXXXX,_______X,XXX_____,
  _XXX___X,XXXXXXXX,X_____XX,XXX_____,
  _XXX___X,X_XXXXXX,XX____XX,XX______,
  _XXX____,__XXXXXX,XX____XX,XX______,
  _XXX___X,XXXXXXXX,X_____XX,XX______,
  _XXX___X,XXXXXXX_,______XX,XX______,
  _XXX____,XXXXXXXX,X____XXX,XX______,
  __XX____,___XXXX_,XXX__XXX,X_______,
  ________,___XXXX_,XXXXXXXX,X_______,
  ________,___XXX__,__XXXXXX,________,
  ________,___XXX__,___XXXXX,________,
  ________,____XX__,___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_5668[132] = { /* code 5668 */
  ________,____XX__,_______X,XXX_____,
  ________,__XXXXX_,_____XXX,XXXX____,
  ________,_XXXXXXX,XXXXXXXX,XXXXX___,
  _______X,XXXXXXXX,XXXXXXX_,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX__X,XXXX____,
  _____XXX,X__XXXXX,_XXXX_XX,XXX_____,
  _____XXX,X_XXXXX_,_XXXXXXX,XXX_____,
  _____XXX,XXXXXXX_,_XXXXXXX,XX______,
  _____XXX,XXXXXXX_,_XXXXXXX,XX______,
  _____XXX,XXXXXXXX,_XXXXXXX,XX______,
  ______XX,XXXXXXXX,X_XX____,________,
  _______X,X__XXXXX,X___XXXX,X_______,
  ________,____XXXX,X____XXX,XX______,
  ________,____XXXX,___XXXXX,XXXXX___,
  ________,___XXXXX,XXXXXXXX,XXXXX___,
  XX____XX,XXXXXXXX,XXXX____,___XX___,
  XXXXXXXX,XXXXXXX_,_XXXXX__,________,
  XXXXXXXX,XXXXXXX_,__XXXXX_,________,
  XXXXXXX_,_XXXXX__,___XXXXX,________,
  _XXX____,XXXXX___,__XXXXXX,________,
  ______XX,XXXXX___,XXXXXXXX,X_______,
  ______XX,XXX_____,____XXXX,XXX_____,
  ________,__XXXXXX,XXXXXXXX,XXXX____,
  ____XX__,XXXXXXX_,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXX_,XXXXXX_X,XXXX____,
  ____XXXX,XXXXXXX_,XXXX___X,XXX_____,
  ____XXXX,__XXXX__,XXXX__XX,XX______,
  ____XXXX,_XXXXX__,XXXXXXXX,XX______,
  _____XXX,XXXXXX__,XXXXXXXX,XXX_____,
  _____XXX,XXXXXX__,_XXX____,XX______,
  _____XXX,XXX_____,________,________,
  ______XX,X_______,________,________,
  _______X,X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_76DB[185] = { /* code 76DB */
  ________,__XXX___,________,________,________,
  ________,___XXXXX,________,________,________,
  ________,____XXXX,X_______,________,________,
  ________,_____XXX,XX___XXX,XX______,________,
  ________,_____XXX,XX____XX,XXX_____,________,
  ________,______XX,XX_____X,XXX_____,________,
  ________,______XX,XXXXXX__,XX______,________,
  ________,_____XXX,XXXXXX__,________,________,
  ________,___XXXXX,XXXXX___,________,________,
  ________,XXXXXXXX,XXX_____,________,________,
  __XXX__X,XXXXXXXX,XXX_____,________,________,
  __XXX_XX,XXXXXXX_,XXXX____,________,________,
  __XXXXX_,__XX____,XXXX___X,XX______,________,
  __XXXX__,___XXXXX,_XXX___X,XXX_____,________,
  ___XXXX_,__XXXXXX,XXXXX_XX,XXX_____,________,
  ___XXXX_,XXXXXXXX,XXXXX_XX,XX______,________,
  ____XXXX,XXXXXXXX,X_XXXXXX,XX______,________,
  ____XXXX,XXXXXXXX,__XXXXXX,X_______,________,
  ____XXXX,XXXXXXXX,___XXXXX,________,________,
  ____XXX_,___XXXXX,___XXXXX,________,________,
  ___XXXX_,___XXXXX,XX_XXXX_,________,________,
  ___XXXX_,__XXXXXX,XXXXXXX_,________,________,
  ___XXXX_,XXXXXX_X,XXXXXXXX,________,________,
  _XXXXXXX,XXXXXXXX,XXXX_XXX,________,________,
  __XXXXXX,XXXXXXXX,XXXX__XX,X_______,________,
  __XXXXXX,XXXXXXXX,XXX___XX,X_______,________,
  __XXXXXX,XX_XXXXX,XXX____X,XX______,________,
  ____XXXX,XXXXXXXX,XXX____X,XXX___XX,________,
  ____XXX_,XXXXXXXX,XXXX____,XXX___XX,________,
  _____XXX,XXXXXXXX,XXXXX___,XXXX__XX,________,
  ____XXXX,XXXXXXX_,__XXX___,_XXXX_XX,________,
  XXXXXXXX,XX______,________,__XXXXXX,X_______,
  XXXXXXX_,________,________,__XXXXXX,X_______,
  XXXXX___,________,________,___XXXXX,X_______,
  _XX_____,________,________,____XXXX,X_______,
  ________,________,________,_____XXX,X_______,
  ________,________,________,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontxingkai_42_957F[140] = { /* code 957F */
  ________,_XXX____,________,________,
  ________,XXXX____,________,________,
  ________,XXX_____,_XX_____,________,
  ________,XXX_____,XXXXX___,________,
  ________,XXX____X,XXXXX___,________,
  ________,XXX__XXX,XXXXXX__,________,
  ________,XXXXXXXX,XXXXX___,________,
  ________,XXXXXXXX,XXXXX___,________,
  ________,XXXXXXXX,XXX_____,________,
  ________,XXXXXXXX,XX______,________,
  _______X,XXXXXX_X,XX______,________,
  ______XX,XXXX____,XXX_____,________,
  ____XXX_,XXXX____,XXXX____,________,
  ___XX___,XXXX____,XXXX____,________,
  __XX____,XXXX____,XXXX____,________,
  _XX_____,XXXX__XX,XXX_____,________,
  XX______,XXXXXXXX,XX______,________,
  XX______,XXXXXXXX,________,________,
  XXX____X,XXXXXXX_,________,________,
  _XXXXXXX,XXXXXXXX,X_______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  ___XXXXX,XXX__XXX,XXXXXXX_,________,
  ____XXXX,XXX____X,XXXXXXXX,X_______,
  _______X,XX______,XXXXXXXX,XXXXX___,
  _______X,XX______,XXXXXXXX,XXXXXXX_,
  _______X,XX_____X,XX_XXXXX,XXXXXXX_,
  _______X,XX____XX,X___XXXX,XXXXXX__,
  _______X,XX__XXXX,X_______,________,
  _______X,XXXXXXXX,________,________,
  _______X,XXXXXXX_,________,________,
  ________,XXXXXXX_,________,________,
  ________,XXXXXX__,________,________,
  ________,XXXXX___,________,________,
  ________,_XXXX___,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontxingkai_42_CharInfo[6] = {
   {  27,  33,   6,   3,  41, acGUI_Fontxingkai_42_4EAC } /* code 4EAC */
  ,{  38,  29,   2,   4,  41, acGUI_Fontxingkai_42_4EEA } /* code 4EEA */
  ,{  28,  35,   8,   0,  41, acGUI_Fontxingkai_42_5357 } /* code 5357 */
  ,{  30,  33,   5,   3,  41, acGUI_Fontxingkai_42_5668 } /* code 5668 */
  ,{  33,  37,   6,   0,  41, acGUI_Fontxingkai_42_76DB } /* code 76DB */
  ,{  31,  35,   5,   1,  41, acGUI_Fontxingkai_42_957F } /* code 957F */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop6 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop5 = {
   0x76DB /* first character */
  ,0x76DB /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  4] /* address of first character */
  ,&GUI_Fontxingkai_42_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop4 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  3] /* address of first character */
  ,&GUI_Fontxingkai_42_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop3 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  2] /* address of first character */
  ,&GUI_Fontxingkai_42_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop2 = {
   0x4EEA /* first character */
  ,0x4EEA /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  1] /* address of first character */
  ,&GUI_Fontxingkai_42_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontxingkai_42_Prop1 = {
   0x4EAC /* first character */
  ,0x4EAC /* last character  */
  ,&GUI_Fontxingkai_42_CharInfo[  0] /* address of first character */
  ,&GUI_Fontxingkai_42_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontxingkai_42 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,42 /* height of font  */
  ,42 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontxingkai_42_Prop1}
  ,30 /* Baseline */
  ,16 /* Height of lowercase characters */
  ,28 /* Height of capital characters */
};

